# Form implementation generated from reading ui file 'guadarArticulo_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 412)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txt_titulo = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_titulo.setObjectName("txt_titulo")
        self.verticalLayout.addWidget(self.txt_titulo)
        self.txtContenido = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.txtContenido.setObjectName("txtContenido")
        self.verticalLayout.addWidget(self.txtContenido)
        self.btn_guardar_articulo = QtWidgets.QPushButton(parent=Dialog)
        self.btn_guardar_articulo.setObjectName("btn_guardar_articulo")
        self.verticalLayout.addWidget(self.btn_guardar_articulo)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Registrar nuevo articulo"))
        self.txt_titulo.setPlaceholderText(_translate("Dialog", "Titulo"))
        self.txtContenido.setPlaceholderText(_translate("Dialog", "Texto"))
        self.btn_guardar_articulo.setText(_translate("Dialog", "Guardar"))
